### ISSUE TITLE
The execution of Omixer-RPM returned a non-zero exit status.

### ISSUE THREAD

**Issue by saharbagheri** [omixer/omixer-rpmR#10]
Hi,

I'm trying to use my stratified data and see which bacteria produces which GBM/GMM. However when I run the following code I receive this error:

GBMs <- omixerRpm::rpm(x = KOs_final,  module.db = db,annotation=2)

Error: "The execution of Omixer-RPM returned a non-zero exit status. Refer to the exception output for details."

I was wondering if my input should have a specific format. I tried having only a column called Gene_Family (including KOs and taxonomy) and also having two separate columns called KOs and species and in both cases I received the same error. 

Thanks

**Comment by omixer** [comment]
Hi @saharbagheri,

I am guessing this is caused by Java. Do you have Java 8 or higher installed on your system?

For the input format, please refer to the following examples:
 - https://github.com/omixer/omixer-rpmR/blob/main/test/matrix.tsv
 - https://github.com/omixer/omixer-rpmR/blob/main/test/species_matrix.tsv
 
 Hope this helps, and apologies for the delayed response! 

Best regards,
Youssef
