### ISSUE TITLE
NULL for getNames

### ISSUE THREAD

**Issue by Noorehuma** [omixer/omixer-rpmR#11]
Hi,
I have KO annotation file and want to map it GBM db. I am using the R code within this github and get NULL names for getNames function. Is there a possible answer for this?

Thanks

**Comment by omixer** [comment]
Hi @Noorehuma,

Please load the GBMs  with the following command

`db <- loadDB("GBMs.v1.0")`

then run rpm by specifying the GBMs as `module.db`

`mods <- rpm("matrix.tsv", minimum.coverage=0.3, annotation = 1, module.db= db)`

If the above does not solve your issue, could you please provide the script you are running, and the first 5 lines of your KO annotation file?

Best regards,
Youssef

**Comment by Noorehuma** [comment]
Hi Youssef,

After running your specified code, I did get one name of GBM, "p-Cresol synthesis". This is because running <getNames(db, mods@annotation[1,])> gives first predicted module. After this I ran;
<coverage <- asDataFrame(mods, "coverage")>
<write.csv(coverage, "GBM.csv")>, 

Now I have a csv file having 28 GBM. Is that all? What further analysis do you recommend on this? Or I should just proceed with making boxplots etc according to my metadata file? Moreover, my csv file doesn't have row names because when we load the matrix.tsv file, we eliminate row names. Instead it has X values. I hope these values are in order of my sample names.
 
Best Regards,
Noor

**Comment by omixer** [comment]
Hi @Noorehuma,

To get all the names run the following:

`sapply(1:nrow(mods@coverage), function(i) getNames(db, mods@annotation[i,]))`

Otherwise you can create a new dataframe and then save it to a csv file as follows:

`coverage.df <- data.frame(mods@annotation, ModuleName=sapply(1:nrow(mods@coverage), function(i) getNames(db, mods@annotation[i,])), mods@coverage)
 write.table(coverage.df, "GBM.csv", col.names=T, row.names=F, sep=",")
`
You can also repeat the above to get the abundance instead of the coverage.

From here onwards, depending on your scientific question you can do other analyses, but it is ouf of the scope of this package. Please check Bioconductor or other tools like Lefse for downstream analysis

Best regards,
Youssef

**Comment by Noorehuma** [comment]
Thank you so much.
